### ISSUE TITLE
How to Cite the Paper?

### ISSUE THREAD

**Issue by zxl19** [UMich-BipedLab/LiDAR_intrinsic_calibration#1]
Hi, @brucejk !

Thank you for your excellent work! I would like to cite your paper in my research. However, I can't find it on arxiv for now. Are there any alternative ways to cite your paper?

Best Wishes.

**Comment by brucejk** [comment]
Hi, 

Thanks for your comments and I am glad you found the work useful! 


Please cite it as:

```
@article{huang2020global,
  title={Global Unifying Intrinsic Calibration for Spinning and Solid-State LiDARs},
  author={Huang, Jiunn-Kai and Feng, Chenxi and Achar, Madhav and Ghaffari, Maani and Grizzle, Jessy W},
  journal={arXiv preprint arXiv:2012.03321},
  year={2020}
}
```
