### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wuying484** [UMich-BipedLab/LiDAR_intrinsic_calibration#3]
For the first and third installations, the server returned 404. Is this because you didn't update it?

**Comment by brucejk** [comment]
Hi,

I changed the names of the packages so the links were changed accordingly. They can be found [here](https://github.com/UMich-BipedLab/global_sim3_solver) and [here](https://github.com/UMich-BipedLab/LiDAR_intrinsic_calibration)

Sorry for the confusion!
