### ISSUE TITLE
Calibration Fail !

### ISSUE THREAD

**Issue by Tony-TF** [UMich-BipedLab/LiDAR_intrinsic_calibration#5]
Thank you for the open source tool，But the calibration tool  failed during my Case。
I used the tetrahedron in the article to calibrate the Velodyle VLP-16，But the calibration results are not accurate
The result 

All processes has finished
ans =

  1×7 table

    mean_original    mean_calibrated    mean_percentage    std_original    std_calibrated    thickness_original    thickness_calibrated
    _____________    _______________    _______________    ____________    ______________    __________________    ____________________

      0.007462           0.00518            0.30582         0.0064563        0.0063288            0.072424               0.053788      

ans =

  1×5 table

    mean_original    mean_calibrated    mean_percentage    std_original    std_calibrated
    _____________    _______________    _______________    ____________    ______________

      0.011139          0.0057358           0.48506         0.0072557        0.0071421   

ans =

  1×5 table

    mean_original    mean_calibrated    mean_percentage    std_original    std_calibrated
    _____________    _______________    _______________    ____________    ______________

      0.015194          0.0054396           0.64199         0.0071618        0.0068011   

ans =

  1×5 table

    mean_original    mean_calibrated    mean_percentage    std_original    std_calibrated
    _____________    _______________    _______________    ____________    ______________

         NaN               NaN                NaN              NaN              NaN      

All processes has finished.

![Screenshot from 2022-04-07 11-31-31](https://user-images.githubusercontent.com/35761167/162114755-6801a879-9f32-45fc-a276-69495210c284.png)
![Screenshot from 2022-04-07 11-31-17](https://user-images.githubusercontent.com/35761167/162114757-f70f76c6-269d-4cdc-ba8e-214faaf4476e.png)
![Screenshot from 2022-04-07 11-28-23](https://user-images.githubusercontent.com/35761167/162114760-5ee8eb57-6f37-4c99-ad92-42208bec58d4.png)

The Calib_parem  translation vector is  Incorrect，X and Z offset is too large。
The train data  is
![Screenshot from 2022-04-07 11-41-49](https://user-images.githubusercontent.com/35761167/162115805-f316ae65-d8da-4be4-bcc4-07f086b30b1a.png)
![Screenshot from 2022-04-07 11-42-30](https://user-images.githubusercontent.com/35761167/162115846-cf81c4f1-6f2c-4e61-8c20-0b610efec7ad.png)

Can you tell me which step is wrong?  Thanks!

**Comment by brucejk** [comment]
Can you explain how did you calibrate the system and what is the process a bit more?
